// <auto-generated />
using System;
using JioCxRcsWrapper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JioCxRcsWrapper.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504193535_RemoveCredits")]
    partial class RemoveCredits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.CampaignMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignMessages");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.CampaignQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("CampaignQueueItems");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.ClientBrandingSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "IsDefault");

                    b.ToTable("ClientBrandingSettings");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "MobileNumber")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.MessageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "ContactId", "Timestamp");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("LocalMediaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MediaContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RcsMediaUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Name");

                    b.ToTable("MessageTemplates");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "View"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Add"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Download"
                        });
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Delivered")
                        .HasColumnType("int");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<int>("TotalSent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "Module")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Module = "Dashboard",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Module = "Dashboard",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Module = "Dashboard",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Module = "Dashboard",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Module = "Dashboard",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Module = "Clients",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            Module = "Clients",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            Module = "Clients",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            Module = "Clients",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            Module = "Clients",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            Module = "Users",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            Module = "Users",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            Module = "Users",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            Module = "Users",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            Module = "Users",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            Module = "Campaigns",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            Module = "Campaigns",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            Module = "Campaigns",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            Module = "Campaigns",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            Module = "Campaigns",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            Module = "Reports",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            Module = "Reports",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            Module = "Reports",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            Module = "Reports",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            Module = "Reports",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            Module = "AuditLogs",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            Module = "AuditLogs",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            Module = "AuditLogs",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            Module = "AuditLogs",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            Module = "AuditLogs",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            Module = "Media",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            Module = "Media",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 33,
                            Module = "Media",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 34,
                            Module = "Media",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 35,
                            Module = "Media",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 36,
                            Module = "Dashboard",
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            Module = "Campaigns",
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            Module = "Reports",
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            Module = "Media",
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            Module = "Campaigns",
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            Module = "Campaigns",
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            Module = "Campaigns",
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            Module = "Reports",
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            Module = "Dashboard",
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 45,
                            Module = "Reports",
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 46,
                            Module = "Reports",
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            Module = "MessageBuilder",
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 48,
                            Module = "MessageBuilder",
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 49,
                            Module = "MessageBuilder",
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 50,
                            Module = "MessageBuilder",
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 51,
                            Module = "MessageBuilder",
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 52,
                            Module = "MessageBuilder",
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 53,
                            Module = "MessageBuilder",
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            Module = "MessageBuilder",
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            Module = "MessageBuilder",
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 56,
                            Module = "MessageBuilder",
                            PermissionId = 1,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.UploadedMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.ToTable("UploadedMedia");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@local.test",
                            IsActive = true,
                            Name = "System Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAECm1p9KdJkz9/8pNO5Yb/5v6s+zxD9nBzWjydYpQ3ytXUvutLz6rvpLLecJxW7iWVQ==",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("JioCxRcsWrapper.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JioCxRcsWrapper.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.User", b =>
                {
                    b.HasOne("JioCxRcsWrapper.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JioCxRcsWrapper.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("JioCxRcsWrapper.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
